[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source = '''
   call deoplete#custom#option({
   \ 'enable_at_startup': 1,
   \ 'auto_complete_delay': 0,
   \ 'auto_complete_start_length': 1,
   \ 'enable_camel_case': 0,
   \ 'enable_ignore_case': 0,
   \ 'enable_refresh_always': 0,
   \ 'enable_smart_case': 1,
   \ 'max_list': 1000,
   \ })
   inoremap <expr><tab> pumvisible() ? "\<C-n>" :
      \ neosnippet#expandable_or_jumpable() ?
      \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
   call deoplete#custom#var('omni', 'input_patterns', {
      \ 'tex': g:vimtex#re#deoplete
      \})
'''
on_i = 1


[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
